### ISSUE TITLE
Support params

### ISSUE THREAD

**Issue by leesiongchan** [alisd23/mobx-react-router#12]
Currently there is only `location` has transformed into observable object and that's great. But why didn't you do the same for `params`? Are there any concerns that I might have missed out?

**Comment by alisd23** [comment]
Hi, good question.

Well I know for sure that `react-router-redux` (which this is very much based off) doesn't include params in the global store. I think it's because params are parsed when the route matches not when the location changes - the latter being what this library listens to. To get the params into state, we'd have to hook into the route component matching itself, which would require a pretty big rewrite of the API.

I suppose you could quite easily make some higher order component which wraps your route components, the sets the params in your store when the route changes.

**Comment by andrefox333** [comment]
I wish it did support params as well but if I really need it in my component, I decorate it with`withRouter` from react-router-dom.

import { withRouter } from 'react-router-dom';

```
@withRouter
export default class MyComponent extends Component {
  render() {
    const { match } = this.props; //what you will get from withRouter which has a bunch of router configs and the params itself.
    ...
  }
}```
