### ISSUE TITLE
goBack doesn't update the Route components the first time

### ISSUE THREAD

**Issue by marcofugaro** [alisd23/mobx-react-router#23]
Hey, I was playing around with your example and added a couple of `Route` components just to test it, I noticed that calling `goBack` or pushing back from the browser updates the url but has no effect the first time on the Route components, why do you think that happens? I would help but have no idea.

Here is the example 
https://mobx-react-router-test-wyyurqrtst.now.sh/

And here is the code 
https://github.com/marcofugaro/mobx-react-router-test

**Comment by alisd23** [comment]
Hey this looks like the same issue as #22.

This is caused by issues with react-router using `context`, which has some strange behaviour relating to any parent components implementing a `shouldComponentUpdate` function. Basically it's an issue with the `react-router` implementation (combined with MobX/Redux).

Simply wrapping any component which renders `<Route />` components (so the `App` component in your case) with React Router's `withRouter` higher order component should force the Route's to re-render correctly.

**Comment by marcofugaro** [comment]
Whoa, didn't know something like `withRouter` existed, somehow it isn't even mentioned in [this doc section](https://reacttraining.com/react-router/web/guides/dealing-with-update-blocking).

Thought it was that kind of blocking, thanks!
