### ISSUE TITLE
Navigate from imported store?

### ISSUE THREAD

**Issue by MovingGifts** [alisd23/mobx-react-router#29]
Using `mobx-react-router`, would I be able to navigate from a mobx store (not just a react component)  that is aware of the route history/location by importing it and using? Something like:

```
import { NavigationStore } from 'navigation-store';

class ContactStore {
  @action contactForm(name, message){
    // Some logic runs here

    // Then navigate back or success

    // Go back
    NavigationStore.goBack();

    // Or Navigate to Route
    NavigationStore.push('/success'); 
  }
}
```
I really need to be able to use `react-router` the same way (import the `NavigationStore` and call the store's available methods to navigate) since I have it working with `react-navigation` with RN, but trying to reuse a web version of the store with `mobx-react-router` for web.

**Comment by alisd23** [comment]
Well this issue is a more high-level issue with a Mobx store system. Mobx says nothing about how to communicate between stores: that will be an issue for your project structure to solve. But yes there'll be nothing stopping you calling the store methods once you get access to it here.

You might have to do some naive 'dependency injection' approach like Angular. Maybe google around for a solution.

**Comment by abelkbil** [comment]
@MovingGifts 
https://mobx.js.org/best/store.html#combining-multiple-stores

@alisd23 , @MovingGifts 
Hope. you managed it earlier. I would request you to share, How to make the route navigation from store.

Thank you.

**Comment by stephane-r** [comment]
Finaly, not possible to use in store ?
