### ISSUE TITLE
Any sample config for hotreload?

### ISSUE THREAD

**Issue by njleonzhang** [alisd23/mobx-react-router#30]
would you please provide a sample project which hotreload can work

**Comment by alisd23** [comment]
I don't think that's really a responsibility of this library. Personally I haven't used MobX with hot reloading at all. It should be possible though by following the webpack hot reloading docs (if you're using webpack).

**Comment by njleonzhang** [comment]
@alisd23 yeah, but if you can provide a sample, it will be easy for user to make everything work, which also benefits this project.... I am trying to make things work, but I am not familiar with React tech stack......

**Comment by alisd23** [comment]
Well I'm a bit confused because the routing store provided by this library doesn't need to be hot reloading, because it's an external library.

If you're talking about hot reloading **your own** Mobx stores then there's probably an example on a Mobx issue somewhere.

Here's an issue to get you started - I found it with a quick google: https://github.com/mobxjs/mobx/issues/254
