### ISSUE TITLE
Support mobx-state-tree

### ISSUE THREAD

**Issue by marcofugaro** [alisd23/mobx-react-router#38]
Right now you can use `mobx-react-router` with `mobx-state-tree` treating the router as a generic `types.frozen`, it works fine but `mobx-state-tree` doesn't trigger an update when location changes, because it's a property of the frozen object. [Here is an example of it](https://github.com/mobxjs/mobx-state-tree/issues/665).

A solution would be to treat the router as a real branch in MST, with a model and everything like demonstrated [in this example](https://codesandbox.io/s/913n1q60xw). 

Probably a `RouterStore` exported for MST would work, something like `import { RouterStore } from 'mobx-react-router/mst'`. Do you wish to support `mobx-state-tree`?

**Comment by alisd23** [comment]
I'm open to it, and it doesn't seem like too much extra code.

However, I'm just considering how to go about it. As there will need to be a peer dependency on `mobx-state-tree` in this library (because of the `types.model` stuff), even people not using `mobx-state-tree` will get "missing peer dependencies" warnings constantly.

It seems that the best way to go about this (unfortunately) might be to create *another* router binding library specifically for `mobx-state-tree`.
`mobx-state-tree` has such a different API to pure `mobx` observables, that trying to merge router bindings for both probably doesn't make sense.

Open for discussion though.

**Comment by marcofugaro** [comment]
True, I'm also for the idea of a different library, quite some things would be different.

For example you wouldn't need the `subscribe` and `unsubscribe` methods with mobx-state-tree, thanks to its helper function `onSnapshot` (or others) to which you can pass the router branch.

For example this is my simple implementation of the syncHistoryWithStore function
```js
export const syncHistoryWithStore = (history, store) => {
  // Set initial history and location
  store._setHistory(history)
  store._setLocation(history.location)

  // Handle update from history object
  history.listen(location => store._setLocation(location))

  return history
}
```

**Comment by alisd23** [comment]
I guess we still might want the `unsubscribe` method exposed, as that gives the user a way of disconnecting the router state from the history (unsubscribing the store from the browser history) if they **really ** needed to.

So for the name: I guess `mobx-state-tree-react-router` rolls off the tongue *nicely*...
Maybe just `mst-react-router` would work.

I'd be happy to quickly whip up the library in the next couple of days to get a basic first concept going. 
I'll link it back on here when it's up so you can take a look and suggest any changes 👍

**Comment by alisd23** [comment]
Took a bit longer than I hoped, but `v1.0.0` is now live: https://github.com/alisd23/mst-react-router.

Thanks @dbertella and @marcofugaro for the help with the initial investigation/code.

🎉 🎉 🎉 🌮
