### ISSUE TITLE
TS : history definition error

### ISSUE THREAD

**Issue by pierre-H** [alisd23/mobx-react-router#7]
Hi,

I use React with TS (I use [react-scripts-ts](https://github.com/wmonk/create-react-app-typescript) and when I define the Router history, I've got this error :
```
Error in ./src/index.tsx
(32,15): error TS2322: Type 'SynchronizedHistory' is not assignable to type 'History | undefined'.
  Type 'SynchronizedHistory' is not assignable to type 'History'.
    Types of property 'listenBefore' are incompatible.
      Type '(hook: TransitionHook) => UnsubscribeCallback' is not assignable to type '(hook: TransitionHook) => () => void'.
        Types of parameters 'hook' and 'hook' are incompatible.
          Type 'History.History.TransitionHook' is not assignable to type 'MobxReactRouter.TransitionHook'.
            Types of parameters 'location' and 'location' are incompatible.
              Type 'MobxReactRouter.Location' is not assignable to type 'History.Location'.
                Property 'query' is optional in type 'Location' but required in type 'Location'.
```

It comes from this line : `<Router history={history} >`
I did exactly like the documentation : `const history = syncHistoryWithStore(browserHistory, routingStore);
`

Thank you for your work !

**Comment by alisd23** [comment]
Hmm interesting. I'll admit I haven't actually tried using typescript with this library yet. The PR for typings was only just added. Any idea what could be the issue @rokoroku?

**Comment by rokoroku** [comment]
It's because of the type ``SynchronizedHistory``.
Since ``syncHistoryWithStore(...)`` will add ``unsubscribe()`` method to the  ``history``, I added it to the type declarations.  ( means returned history is typeof ``SynchronizedHistory``, not typeof ``History``)

However, if you have a look into the implementation, ``syncHistoryWithStore()`` method simply adds a listener via the ``history.listen(...)``, so it's basically same using the ``browserHistory`` as the ``Router``'s prop.
```jsx
<Router history={browserHistory} >
{/* is same as */}
<Router history={synchronizedHistory as any as History} >
```

If we remove the type ``SynchronizedHistory``, the ``unsubscribe()` method is not gonna visible anywhere. What's your thought, @alisd23 ?

**Comment by rokoroku** [comment]
Oh, it was a problem with **deprecated** properties rather than with ``SynchronizedHistory``.

Since react-router still use type definitions of history **v2** (even they are currently on **v3**), the v3 based ``History`` does not compatible to this ... (see [history#changelog](https://github.com/mjackson/history/blob/2c7a038c8221ab50d6d2c8b27571eed414dc0119/CHANGES.md), they always have lots of breaking changes)

So, It's better to add the deprecated methods. I'll make PR soon.
